<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Blog\Module'                        => __DIR__ . '/Module.php',
    'Blog\Controller\ViewController' => __DIR__ . '/src/Blog/Controller/ViewController.php',
    'Blog\Framework\TestCase'        => __DIR__ . '/tests/Blog/Framework/TestCase.php',
    'Blog\SampleTest'                => __DIR__ . '/tests/Blog/SampleTest.php',
);